### ISSUE TITLE
Wrong datetime formating on string openApiType?

### ISSUE THREAD

**Issue by jakovec** [VitexSoftware/php-vitexsoftware-rbczpremiumapi#1]
https://github.com/VitexSoftware/php-vitexsoftware-rbczpremiumapi/blame/7a8a2841a6881dc73edd31a7d0ddf234686c812a/lib/ObjectSerializer.php#L242

Should not this be like this? 
`if ($openApiType === "string" && $value instanceof \DateTime) {`

**Comment by Vitexus** [comment]
I'll throw an :eye: on it.

**Comment by Vitexus** [comment]
> https://github.com/VitexSoftware/php-vitexsoftware-rbczpremiumapi/blame/7a8a2841a6881dc73edd31a7d0ddf234686c812a/lib/ObjectSerializer.php#L242
> 
> Should not this be like this? `if ($openApiType === "string" && $value instanceof \DateTime) {`

Could you please give me example of API call which returns response with this date somehow ?

I have only integer in my examples ...


![image](https://github.com/user-attachments/assets/936409f1-5d1c-4dd9-ab74-f951b33c996e)

Thanks

**Comment by jakovec** [comment]
sure, getTransactionList uses that:

```
$xRequestId = 'test_call';
$accountNumber = '1234567890';
$currencyCode = 'CZK';
$from = new \DateTime();
$from->modify("-1 days");
$to = new \DateTime();
$page = 1;

$result = $apiInstance->getTransactionList($xRequestId, $accountNumber, $currencyCode, $from, $to,  $page);
```

there is also a problem with ObjectSerialier that it uses a format
`\DateTime::ATOM
`
by default (line 47) which is not accepted by the RBPremiumAPI, which needs format: 2021-08-01 or 2021-08-01T10:00:00.0Z

**Comment by jakovec** [comment]
seems perfect!
